version: "3"

services:
  app:
    image: node:20-alpine
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      HTTP_PORT: ${HTTP_PORT}
    working_dir: /home/app
    command:
      - /bin/sh
      - -c
      - |
        npm i
        node server.js
    volumes:
      - "./:/home/app"
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - redis
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "${REDIS_PORT}:6379"